### ISSUE TITLE
Missing Client ID error

### ISSUE THREAD

**Issue by kaushalrohit12** [trafficgate/linkshare-api#8]
I am trying to use this library to search product, but its currently giving me a fatal error:

```
Fatal error: Uncaught Linkshare\Exceptions\MissingFieldException: Missing fields: client_id in /linkshare-api-master/src/Api/AbstractApi.php:60
Stack trace:
#0 /linkshare-api-master/src/Api/AbstractLinkshareApi.php(49): Linkshare\Api\AbstractApi->__construct(Array)
#1 /linkshare-api-master/examples/product_search_example.php(34): Linkshare\Api\AbstractLinkshareApi->__construct(Array)
#2 {main} thrown in /linkshare-api-master/src/Api/AbstractApi.php on line 60
```

**Comment by ikari7789** [comment]
Did you have `client_id` set?

**Comment by ikari7789** [comment]
Please make a new issue if this is still an issue.
